### ISSUE TITLE
Lost watch events

### ISSUE THREAD

**Issue by madtrick** [bonifaido/rust-zookeeper#98]
Hi,

In my local setup I have seen several times how watch events seem to be lost by the Zookeper client.  This is the code where I watch for events:

```rust
fn main () {
    let zk = ZooKeeper::connect("localhost:2181", Duration::from_secs(15), LoggingWatcher).unwrap();

    zk.add_watch(
        "/nodes",
        AddWatchMode::PersistentRecursive,
        |event: WatchedEvent| {
            println!("Event {:?}, path {:?}", event, event.path);
        },
    )
    .unwrap();


    loop {
        thread::sleep(Duration::from_secs(1800));
    }
}
```

And I'm running zookeeper via docker compose

```yaml
  zookeeper:
    image: zookeeper
    restart: always
    ports:
      - 2181:2181
  zookeeper-cli:
    image: zookeeper
    command: zkCli.sh -server zookeeper
```

If I watch events from the Zookeeper CLI I see all of them, however some are not "seen" by the Zookeeper rust client. For example, in the screenshot below you can see a `NodeCreated` and `NodeDeleted` for the path `/nodes/node0000000079` in the CLI.

![image](https://github.com/bonifaido/rust-zookeeper/assets/48772/b8557a00-0faf-48de-81f8-125a20dea5d2)

But I only get one watch in rust

![image](https://github.com/bonifaido/rust-zookeeper/assets/48772/980f0eac-b0ba-4e92-b2f8-b0df728541a6)

Is this a bug in the Zookeeper rust client or should I be looking elsewhere?
